name = "stemify"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

account_id = "${CF_ACCOUNT_ID}"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
